# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
title: David Wasser, Pianist
email:
description: >- # this means to ignore newlines until "baseurl:"
  A website spotlighting the music of David Wasser, pianist.
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Denver 
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "David Wasser"
  avatar : "/images/david-wasser-2015-concert--1024x731.jpg"
  bio    : "Pianist."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.davidwasser.com/"

footer:
  links:

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: false
      header:
        overlay_color: "#5e616c"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  composers:
    output: true
    permalink: /:collection/:path/
